name: Merge workflow

on: [ pull_request ]

jobs:
    test:
        runs-on: ${{ matrix.os }}
        strategy: 
            matrix: 
                os: [ ubuntu-latest, macos-latest, windows-latest ]
        steps:
            - uses: actions/checkout@v4
            - run: python main.py
            - run: python demo.py
        